// Generated by tools/sync-i18n.mjs. Edit i18n.config.json and source catalogs.
import { ko as l0 } from "./ko";
import type { Locale } from './registry.generated';
export type MessageCatalog = { [K in keyof typeof l0]: (typeof l0)[K] extends (...args: infer A) => infer R ? (...args: A) => R : string };
export type MessageKey = keyof MessageCatalog;
export const catalogs: Record<Locale, MessageCatalog> = {"ko-KR":l0};
