// Generated by tools/sync-i18n.mjs. Edit i18n.config.json and source catalogs.
export const SUPPORTED_LOCALES = [
  "ko-KR"
] as const;
export type Locale = (typeof SUPPORTED_LOCALES)[number];
export const SOURCE_LOCALE = "ko-KR" as const;
export const DEFAULT_LOCALE: Locale = "ko-KR";
export const FALLBACK_CHAIN: readonly Locale[] = [
  "ko-KR"
];
export const LOCALE_OPTIONS = [
  {
    "tag": "ko-KR",
    "label": "한국어",
    "direction": "ltr",
    "catalog": "./ko",
    "export": "ko"
  }
] as const;
export function isLocale(value: unknown): value is Locale { return typeof value === "string" && (SUPPORTED_LOCALES as readonly string[]).includes(value); }
export function matchLocale(value: string): Locale | undefined { const tag=value.toLowerCase().replaceAll("_","-"); return SUPPORTED_LOCALES.find(l=>l.toLowerCase()===tag) ?? SUPPORTED_LOCALES.find(l=>l.split("-")[0]===tag.split("-")[0]); }
export function resolveLocale(candidates: readonly (string | null | undefined)[]): Locale { for(const candidate of candidates){if(!candidate)continue; const match=matchLocale(candidate);if(match)return match;}return DEFAULT_LOCALE; }
