import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { synchronizePolicies } from './sync-policy-links.mjs';

function fixture(run) {
  const root = mkdtempSync(join(tmpdir(), 'policy-links-'));
  const hubConfig = join(root, 'hub');
  const options = { hubConfig, output: join(root, 'generated.ts'), snapshotFile: join(root, 'snapshot.json') };
  const data = { policySite: { origin: 'https://policies.example.test', paths: { privacyPolicy: '/privacy/{id}', accountDeletion: '/privacy/{id}/delete-account', support: '/support/{id}' } } };
  mkdirSync(join(hubConfig, 'apps', 'example'), { recursive: true });
  writeFileSync(join(hubConfig, 'apps', 'example', 'policy.json'), '{}');
  writeFileSync(join(hubConfig, 'portfolio.json'), JSON.stringify(data));
  try { run(options, data); } finally { rmSync(root, { recursive: true, force: true }); }
}

test('source and snapshot checks verify generated bytes after synchronization', () => fixture((options) => {
  assert.equal(synchronizePolicies({ ...options, mode: 'sync' }), 'source-synchronized');
  assert.equal(synchronizePolicies({ ...options, mode: 'source' }), 'source-verified');
  assert.match(synchronizePolicies({ ...options, mode: 'snapshot' }), /Hub freshness NOT checked/);
}));
test('a missing Hub fails source verification, while an explicit snapshot check remains available', () => fixture((options) => {
  synchronizePolicies({ ...options, mode: 'sync' });
  rmSync(options.hubConfig, { recursive: true });
  assert.throws(() => synchronizePolicies({ ...options, mode: 'source' }), /NOT performed/);
  assert.match(synchronizePolicies({ ...options, mode: 'snapshot' }), /snapshot-verified/);
}));
test('source changes and generated output changes fail their corresponding checks', () => fixture((options, data) => {
  synchronizePolicies({ ...options, mode: 'sync' });
  data.policySite.origin = 'https://changed.example.test';
  writeFileSync(join(options.hubConfig, 'portfolio.json'), JSON.stringify(data));
  assert.throws(() => synchronizePolicies({ ...options, mode: 'source' }), /differs from Hub/);
  writeFileSync(options.output, '// incorrect manual edit');
  assert.throws(() => synchronizePolicies({ ...options, mode: 'snapshot' }), /differ from the snapshot/);
}));
test('invalid templates and snapshot digests fail closed', () => fixture((options, data) => {
  synchronizePolicies({ ...options, mode: 'sync' });
  const snapshot = JSON.parse(readFileSync(options.snapshotFile, 'utf8'));
  snapshot.sourceDigest = 'incorrect';
  writeFileSync(options.snapshotFile, JSON.stringify(snapshot));
  assert.throws(() => synchronizePolicies({ ...options, mode: 'snapshot' }), /digest/);
  data.policySite.paths.support = '//untrusted.example/{id}';
  writeFileSync(join(options.hubConfig, 'portfolio.json'), JSON.stringify(data));
  assert.throws(() => synchronizePolicies({ ...options, mode: 'sync' }), /invalid policy path/);
}));
