import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { synchronizePolicies } from './sync-policy-links.mjs';

test('app-owned policy URLs do not require a central policy binding', () => fixture((options) => {
  rmSync(join(options.hubConfig, 'apps', 'example', 'policy.json'));
  writeFileSync(join(options.hubConfig, 'apps', 'example', 'app.json'), JSON.stringify({
    store: { policyPublication: 'app-owned', privacyPolicyUrl: 'https://example.test/legal/privacy',
      accountDeletionUrl: 'https://example.test/legal/delete', supportUrl: 'https://example.test/legal/' },
    reviewPassword: 'fixture-private-value',
  }));
  assert.equal(synchronizePolicies({ ...options, mode: 'sync' }), 'source-synchronized');
  assert.match(readFileSync(options.output, 'utf8'), /https:\/\/example\.test\/legal\/privacy/);
  assert.doesNotMatch(readFileSync(options.output, 'utf8'), /reviewPassword|fixture-private-value/);
}));

function fixture(run) {
  const root = mkdtempSync(join(tmpdir(), 'policy-links-'));
  const hubConfig = join(root, 'hub');
  const options = { hubConfig, output: join(root, 'generated.ts'), snapshotFile: join(root, 'snapshot.json') };
  const data = { policySite: { origin: 'https://policies.example.test', paths: { privacyPolicy: '/privacy/{id}', accountDeletion: '/privacy/{id}/delete-account', support: '/support/{id}' } } };
  mkdirSync(join(hubConfig, 'apps', 'example'), { recursive: true });
  writeFileSync(join(hubConfig, 'apps', 'example', 'policy.json'), '{}');
  writeFileSync(join(hubConfig, 'apps', 'example', 'app.json'), '{"store":{}}');
  writeFileSync(join(hubConfig, 'portfolio.json'), JSON.stringify(data));
  try { run(options, data); } finally { rmSync(root, { recursive: true, force: true }); }
}

test('source and snapshot checks verify generated bytes after synchronization', () => fixture((options) => {
  assert.equal(synchronizePolicies({ ...options, mode: 'sync' }), 'source-synchronized');
  assert.equal(synchronizePolicies({ ...options, mode: 'source' }), 'source-verified');
  assert.match(synchronizePolicies({ ...options, mode: 'snapshot' }), /Hub freshness NOT checked/);
}));
test('a missing Hub fails source verification, while an explicit snapshot check remains available', () => fixture((options) => {
  synchronizePolicies({ ...options, mode: 'sync' });
  rmSync(options.hubConfig, { recursive: true });
  assert.throws(() => synchronizePolicies({ ...options, mode: 'source' }), /NOT performed/);
  assert.match(synchronizePolicies({ ...options, mode: 'snapshot' }), /snapshot-verified/);
}));
test('source changes and generated output changes fail their corresponding checks', () => fixture((options, data) => {
  synchronizePolicies({ ...options, mode: 'sync' });
  data.policySite.origin = 'https://changed.example.test';
  writeFileSync(join(options.hubConfig, 'portfolio.json'), JSON.stringify(data));
  assert.throws(() => synchronizePolicies({ ...options, mode: 'source' }), /differs from Hub/);
  writeFileSync(options.output, '// incorrect manual edit');
  assert.throws(() => synchronizePolicies({ ...options, mode: 'snapshot' }), /differ from the snapshot/);
}));
test('invalid templates and snapshot digests fail closed', () => fixture((options, data) => {
  synchronizePolicies({ ...options, mode: 'sync' });
  const snapshot = JSON.parse(readFileSync(options.snapshotFile, 'utf8'));
  snapshot.sourceDigest = 'incorrect';
  writeFileSync(options.snapshotFile, JSON.stringify(snapshot));
  assert.throws(() => synchronizePolicies({ ...options, mode: 'snapshot' }), /digest/);
  data.policySite.paths.support = '//untrusted.example/{id}';
  writeFileSync(join(options.hubConfig, 'portfolio.json'), JSON.stringify(data));
  assert.throws(() => synchronizePolicies({ ...options, mode: 'sync' }), /invalid policy path/);
}));

test('app-owned policy destinations survive public projection without exposing profile data', () => fixture((options) => {
  const store = {
    policyPublication: 'app-owned',
    privacyPolicyUrl: 'https://product.example.test/legal/privacy',
    accountDeletionUrl: 'https://product.example.test/legal/account-deletion',
    supportUrl: 'https://product.example.test/legal/',
    reviewPassword: 'fixture-private-value',
  };
  const profile = join(options.hubConfig, 'apps', 'example', 'app.json');
  writeFileSync(profile, JSON.stringify({ store }));
  synchronizePolicies({ ...options, mode: 'sync' });
  const snapshot = JSON.parse(readFileSync(options.snapshotFile, 'utf8'));
  assert.equal(snapshot.schemaVersion, 2);
  assert.equal(snapshot.projection.publications.example, 'app-owned');
  assert.deepEqual(snapshot.projection.urls.example, {
    privacyPolicy: store.privacyPolicyUrl,
    accountDeletion: store.accountDeletionUrl,
    support: store.supportUrl,
  });
  for (const path of [options.snapshotFile, options.output]) {
    const text = readFileSync(path, 'utf8');
    assert.doesNotMatch(text, /fixture-private-value|reviewPassword/);
    assert.match(text, /https:\/\/product\.example\.test\/legal\/privacy/);
  }
  assert.equal(synchronizePolicies({ ...options, mode: 'source' }), 'source-verified');
  store.supportUrl = 'https://product.example.test/help';
  writeFileSync(profile, JSON.stringify({ store }));
  assert.throws(() => synchronizePolicies({ ...options, mode: 'source' }), /differs from Hub/);
}));

test('retired policy bindings remain available without an active app profile', () => fixture((options) => {
  const directory = join(options.hubConfig, 'apps', 'example');
  rmSync(join(directory, 'app.json'));
  writeFileSync(join(directory, 'retired.json'), JSON.stringify({ id: 'example', store: {} }));
  synchronizePolicies({ ...options, mode: 'sync' });
  const snapshot = JSON.parse(readFileSync(options.snapshotFile, 'utf8'));
  assert.equal(snapshot.projection.publications.example, 'central');
  assert.equal(snapshot.projection.urls.example.privacyPolicy, 'https://policies.example.test/privacy/example');
  assert.equal(synchronizePolicies({ ...options, mode: 'source' }), 'source-verified');
}));

test('central defaults and explicit public overrides use the same canonical URL contract', () => fixture((options) => {
  const profile = join(options.hubConfig, 'apps', 'example', 'app.json');
  writeFileSync(profile, JSON.stringify({ store: { supportUrl: 'https://support.example.test/' } }));
  synchronizePolicies({ ...options, mode: 'sync' });
  const snapshot = JSON.parse(readFileSync(options.snapshotFile, 'utf8'));
  assert.deepEqual(snapshot.projection.urls.example, {
    privacyPolicy: 'https://policies.example.test/privacy/example',
    accountDeletion: 'https://policies.example.test/privacy/example/delete-account',
    support: 'https://support.example.test/',
  });
}));

test('app-owned omissions, unsupported publication and credential-bearing destinations fail closed', () => fixture((options) => {
  const profile = join(options.hubConfig, 'apps', 'example', 'app.json');
  writeFileSync(profile, JSON.stringify({ store: { policyPublication: 'app-owned' } }));
  assert.throws(() => synchronizePolicies({ ...options, mode: 'sync' }), /app-owned policy URL is missing/);
  writeFileSync(profile, JSON.stringify({ store: { policyPublication: 'unknown' } }));
  assert.throws(() => synchronizePolicies({ ...options, mode: 'sync' }), /unsupported policy publication/);
  for (const supportUrl of ['http://support.example.test/', 'https://user:password@support.example.test/']) {
    writeFileSync(profile, JSON.stringify({ store: { supportUrl } }));
    assert.throws(() => synchronizePolicies({ ...options, mode: 'sync' }), /public HTTPS without credentials/);
  }
}));
