import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
const root=resolve(import.meta.dirname,'..');
const literal=v=>JSON.stringify(v,null,2);
const header='// Generated by tools/sync-i18n.mjs. Edit i18n.config.json and source catalogs.\n';
export function projections(config, contract) {
 const tags=config.locales.map(l=>l.tag);
 if(!tags.length||new Set(tags).size!==tags.length)throw Error('Duplicate/empty locales');
 for(const l of config.locales)if(Intl.getCanonicalLocales(l.tag)[0]!==l.tag||!l.label||!['ltr','rtl'].includes(l.direction)||!/^\w+$/.test(l.export)||!/^\.\/[a-zA-Z0-9/.-]+$/.test(l.catalog)||l.catalog.includes('..'))throw Error('Invalid registry entry');
 for(const tag of [config.sourceLocale,config.defaultLocale,...config.fallbackChain])if(!tags.includes(tag))throw Error('Unregistered source/default/fallback');
 const registry=header+[
 `export const SUPPORTED_LOCALES = ${literal(tags)} as const;`,
 'export type Locale = (typeof SUPPORTED_LOCALES)[number];',
 `export const SOURCE_LOCALE = ${literal(config.sourceLocale)} as const;`,
 `export const DEFAULT_LOCALE: Locale = ${literal(config.defaultLocale)};`,
 `export const FALLBACK_CHAIN: readonly Locale[] = ${literal(config.fallbackChain)};`,
 `export const LOCALE_OPTIONS = ${literal(config.locales)} as const;`,
 'export function isLocale(value: unknown): value is Locale { return typeof value === "string" && (SUPPORTED_LOCALES as readonly string[]).includes(value); }',
 'export function matchLocale(value: string): Locale | undefined { const tag=value.toLowerCase().replaceAll("_","-"); return SUPPORTED_LOCALES.find(l=>l.toLowerCase()===tag) ?? SUPPORTED_LOCALES.find(l=>l.split("-")[0]===tag.split("-")[0]); }',
 'export function resolveLocale(candidates: readonly (string | null | undefined)[]): Locale { for(const candidate of candidates){if(!candidate)continue; const match=matchLocale(candidate);if(match)return match;}return DEFAULT_LOCALE; }',
 ].join('\n')+'\n';
 const sourceIndex=config.locales.findIndex(l=>l.tag===config.sourceLocale);
 const manifest=header+config.locales.map((l,i)=>`import { ${l.export} as l${i} } from ${JSON.stringify(l.catalog+config.importExtension)};`).join('\n')+'\n'+`import type { Locale } from './registry.generated${config.importExtension}';\n`+`export type MessageCatalog = { [K in keyof typeof l${sourceIndex}]: (typeof l${sourceIndex})[K] extends (...args: infer A) => infer R ? (...args: A) => R : string };\nexport type MessageKey = keyof MessageCatalog;\nexport const catalogs: Record<Locale, MessageCatalog> = {${tags.map((tag,i)=>`${JSON.stringify(tag)}:l${i}`).join(',')}};\n`;
 const next=structuredClone(contract);Object.assign(next.i18n,{sourceLocale:config.sourceLocale,defaultLocale:config.defaultLocale,supportedLocales:tags,fallbackChain:config.fallbackChain,catalogRoot:config.catalogRoot});
 return new Map([[`${config.output}/registry.generated.ts`,registry],[`${config.output}/catalogs.generated.ts`,manifest],['app.contract.json',literal(next)+'\n']]);
}
export async function sync(write=false) {
 const config=JSON.parse(readFileSync(resolve(root,'i18n.config.json'),'utf8'));
 const contract=JSON.parse(readFileSync(resolve(root,'app.contract.json'),'utf8'));
 const catalogs={};
 for(const l of config.locales){ const path=resolve(root,config.output,l.catalog+'.ts');if(!existsSync(path))throw Error(`Missing catalog ${l.tag}`); catalogs[l.tag]=(await import(pathToFileURL(path)))[l.export]; }
 const source=catalogs[config.sourceLocale];
 const variables=v=>typeof v==='string'?[...v.matchAll(/\{\{?\s*(\w+)\s*\}?\}/g)].map(m=>m[1]).sort().join(','):'';
 for(const [tag,catalog]of Object.entries(catalogs)){
  if(JSON.stringify(Object.keys(catalog).sort())!==JSON.stringify(Object.keys(source).sort()))throw Error(`Catalog keys differ: ${tag}`);
  for(const key of Object.keys(source))if(typeof catalog[key]!==typeof source[key]||typeof catalog[key]==='string'&&(!catalog[key].trim()||variables(catalog[key])!==variables(source[key])))throw Error(`Invalid message ${tag}:${key}`);
 }
 const drift=[];
 for(const [file,body]of projections(config,contract)){const path=resolve(root,file);if(existsSync(path)&&readFileSync(path,'utf8')===body)continue;drift.push(file);if(write)writeFileSync(path,body);}
 if(drift.length&&!write)throw Error(`i18n drift: ${drift.join(', ')}; run pnpm i18n:generate`);
 console.log(`i18n: ${config.locales.length} locales, ${Object.keys(source).length} source keys, ${write?'generated':'checked'} (${drift.length} differences)`);
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href)await sync(process.argv.includes('--write'));
