name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Ensure app-ads.txt in root
        run: |
          if [ -f dist/app-ads.txt ]; then
            echo "app-ads.txt found in dist."
          elif [ -f app-ads.txt ]; then
            echo "Copying app-ads.txt from project root to dist."
            cp app-ads.txt dist/
          else
            echo "❌ app-ads.txt not found. Please add it to project root or dist."
            exit 1
          fi

      - name: Deploy to gh-pages branch
        run: npx gh-pages -d dist -u "github-actions-bot <actions@github.com>" -r https://x-access-token:${GITHUB_TOKEN}@github.com/jim1286/portfolio.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy app-ads.txt to root domain
        run: |
          # Create a temporary directory for root domain files
          mkdir temp-root
          cp dist/app-ads.txt temp-root/
          
          # Create a simple index.html that redirects to portfolio
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;url=https://jim1286.github.io/portfolio/"></head><body>Redirecting...</body></html>' > temp-root/index.html
          
          # Deploy to jim1286.github.io repository
          cd temp-root
          git init
          git config user.name "github-actions-bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy app-ads.txt and redirect"
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/jim1286/jim1286.github.io.git
          git branch -M main
          git push -f origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
