name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # app-ads.txt를 dist 루트에 복사
      - name: Ensure app-ads.txt in root
        run: |
          if [ -f dist/app-ads.txt ]; then
            echo "app-ads.txt found in dist."
          elif [ -f app-ads.txt ]; then
            echo "Copying app-ads.txt from project root to dist."
            cp app-ads.txt dist/
          else
            echo "❌ app-ads.txt not found. Please add it to project root or dist."
            exit 1
          fi

      # dist 내용을 gh-pages 브랜치로 push
      - name: Deploy to gh-pages branch
        run: npx gh-pages -d dist -u "github-actions-bot <actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
